version: "2"
run:
  tests: true
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
        - redundantSprint
        - emptyStringTest
      enabled-tags:
        - diagnostic
        - performance
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - gosec
        path: examples/
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - errcheck
        text: Error return value is not checked
        source: .*\.Close\(\)
    paths:
      - .*\.pb\.go$
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
severity:
  default: error
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nchursin/serenity-go
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - vendor
      - third_party$
      - builtin$
      - examples$
