run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true
  sort-results: true

linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/nchursin/serenity-go
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - redundantSprint
      - emptyStringTest

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: examples/
      linters:
        - errcheck
        - gosec
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "Error return value is not checked"
      linters:
        - errcheck
      source: ".*\\.Close\\(\\)"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false