// Code generated by MockGen. DO NOT EDIT.
// Source: context.go
//
// Generated by this command:
//
//	mockgen -source=context.go -destination=mocks/mock_test_context.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTestContext is a mock of TestContext interface.
type MockTestContext struct {
	ctrl     *gomock.Controller
	recorder *MockTestContextMockRecorder
	isgomock struct{}
}

// MockTestContextMockRecorder is the mock recorder for MockTestContext.
type MockTestContextMockRecorder struct {
	mock *MockTestContext
}

// NewMockTestContext creates a new mock instance.
func NewMockTestContext(ctrl *gomock.Controller) *MockTestContext {
	mock := &MockTestContext{ctrl: ctrl}
	mock.recorder = &MockTestContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestContext) EXPECT() *MockTestContextMockRecorder {
	return m.recorder
}

// Errorf mocks base method.
func (m *MockTestContext) Errorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockTestContextMockRecorder) Errorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockTestContext)(nil).Errorf), varargs...)
}

// FailNow mocks base method.
func (m *MockTestContext) FailNow() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FailNow")
}

// FailNow indicates an expected call of FailNow.
func (mr *MockTestContextMockRecorder) FailNow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailNow", reflect.TypeOf((*MockTestContext)(nil).FailNow))
}

// Failed mocks base method.
func (m *MockTestContext) Failed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Failed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Failed indicates an expected call of Failed.
func (mr *MockTestContextMockRecorder) Failed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Failed", reflect.TypeOf((*MockTestContext)(nil).Failed))
}

// Logf mocks base method.
func (m *MockTestContext) Logf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Logf", varargs...)
}

// Logf indicates an expected call of Logf.
func (mr *MockTestContextMockRecorder) Logf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logf", reflect.TypeOf((*MockTestContext)(nil).Logf), varargs...)
}
